# Option-1 : Creating docker image using command module 
---
- hosts: all
  become: true
  tasks:
  - name: building docker image
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: create tag to image
    command: docker tag simple-devops-image gautam/simple-devops-image

  - name: push to docker hub
    command: docker push gautam/simple-devops-image

  - name: remove docker image
    command: docker rmi simple-devops-image gautam/simple-devops-image
    ignore_errors: yes

# option-2 : creating docker image using docker_image module 

#  tasks:
#  - name: building docker image
#    docker_image:
#      build:
#        path: /opt/docker
#      name: simple-devops-image
#     tag: v1
#     source: build
