apiVersion: v1
kind: Service
metadata:
  name: gautam-service
  labels:
    app: gautam-devops-project
spec:
  selector:
    app: gautam-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080    
      nodePort: 31200
